Trying to get the O2 build with AliRoot workign again
There are several problems:
- AliTPCCommon comes with it's own RTypes definition and also includes
  AliHLTLogging causing duplicate definitions when building with AliRoot
  https://github.com/AliceO2Group/AliTPCCommon/pull/4
- AliTPCCommon pulls in something from AliRoot HLT base and TPC libraries
  so those had to be included in the bucket. This is probably not necessary
  if AliTPCCommon is built correctly
- the main problem is in the pythia library shipped with AliRoot, that means
  there are two pythia libraries in the system with conflicting signatures
  and leading to unresolved symbols as the pythia6 library from AliRoot is
  picked up (and needs lhapdf in addition), while ROOT has been built with the
  standalone pythia6 library
  Compiler error:
    <>/AliRoot/devO2-8/lib/libpythia6.so: undefined reference to `structa_'
    <>/ROOT/v6-12-06-1/lib/libEGPythia6.so: undefined reference to `pyrset_'
    <>/AliRoot/devO2-8/lib/libpythia6.so: undefined reference to `structp_'
    <>/AliRoot/devO2-8/lib/libpythia6.so: undefined reference to `structm_'
    <>/AliRoot/devO2-8/lib/libpythia6.so: undefined reference to `pdfset_'
    <>/AliRoot/devO2-8/lib/libpythia6.so: undefined reference to `pyr_'
    <>/ROOT/v6-12-06-1/lib/libEGPythia6.so: undefined reference to `pyrget_'
    <>/AliRoot/devO2-8/lib/libpythia6.so: undefined reference to `setlhaparm_'
    collect2: error: ld returned 1 exit status
    run/CMakeFiles/o2sim.dir/build.make:197: recipe for target 'bin/o2sim' failed
    make[2]: *** [bin/o2sim] Error 1
  Can probably be solved by changing the sequence of library paths so that ROOT
  and pythia6 come before AliRoot