Trying to debug a problem in the ROOT streamer when reading old MCTruthContainer
The two extracted vectors of the old object do not have the correct data. It appears that
oldObj->GetClass()->GetDataMemberOffset("member name") returns 0 regardsless of the
argument, i.e. it seems that mHeaderArray and mTruthArray are not in the class streamer
info at all.

Code in generated file O2/DataFormats/simulation/G__O2SimulationDataFormat.cxx

break testMCTruthContainer.cxx:291
break G__O2SimulationDataFormat.cxx:253

In TClass::GetDataMemberOffset core/meta/src/TClass.cxx
   │3322    Long_t TClass::GetDataMemberOffset(const char *name) const
   │3323    {
   │3324       TRealData *rd = GetRealData(name);
   │3325       if (rd) return rd->GetThisOffset();
   │3326       if (strchr(name,'[')==0) {
   │3327          // If this is a simple name there is a chance to find it in the
   │3328          // StreamerInfo even if we did not find it in the RealData.
   │3329          // For example an array name would be fArray[3] in RealData but
   │3330          // just fArray in the streamerInfo.
   │3331          TVirtualStreamerInfo *info = const_cast<TClass*>(this)->GetCurrentStreamerInfo();
   │3332          if (info) {
  >│3333             return info->GetOffset(name);
   │3334          }
   │3335       }
   │3336       return 0;
   │3337    }
no read data object found here, so the current streamer info is searched

TStreamerInfo::GetOffset io/io/src/TStreamerInfo.cxx
   |4023    Int_t TStreamerInfo::GetOffset(const char *elementName) const
  >│4024    {
   │4025       if (elementName == 0) return 0;
   │4026
   │4027       Int_t offset = 0;
   │4028       TStreamerElement *elem = (TStreamerElement*)fElements->FindObject(elementName);
   │4029       if (elem) offset = elem->GetOffset();
   │4030
   │4031       return offset;
   │4032    }

(gdb) p fElements
$4 = (TObjArray *) 0x555556e8d7c0
(gdb) p fElements->Print()
Too few arguments in function call.
(gdb) p fElements->Print("")
Collection name='TObjArray', class='TObjArray', size=16
 OBJ: TStreamerSTL	mData
$5 = void

Obviously its not correct to use the current streamer info. Not yet clear if there should be real data objects

Investigating the two StreamerInfo objects
$8 = (const TStreamerInfo * const) 0x555556e8d6d0
(gdb) p ((TStreamerInfo*)0x555556e8d6d0)->fElements->Print("")
Collection name='TObjArray', class='TObjArray', size=16
 OBJ: TStreamerSTL	mData
$9 = void
(gdb) p ((TStreamerInfo*)0x5555565ef890)->fElements->Print("")
Collection name='TObjArray', class='TObjArray', size=16
 OBJ: TStreamerArtificial	@@alloc
 OBJ: TStreamerSTL	mHeaderArray	the header structure array serves as an index into the actual storage (o2::dataformats::MCTruthHeaderElement)
 OBJ: TStreamerSTL	mHeaderArray	the header structure array serves as an index into the actual storage (o2::dataformats::MCTruthHeaderElement)
 OBJ: TStreamerSTL	mTruthArray	the buffer containing the actual truth information (o2::MCCompLabel)
 OBJ: TStreamerSTL	mTruthArray	the buffer containing the actual truth information (o2::MCCompLabel)
 OBJ: TStreamerArtificial	mData
 OBJ: TStreamerArtificial	@@dealloc
$10 = void